### ISSUE TITLE
Organization of the project

### ISSUE THREAD

**Issue by ObaniGemini** [KOBUGE-Games/bob-adventures#4]
## \- First Step
- [ ] Finish the Main Character https://github.com/KOBUGE-Games/bob-adventures/issues/3
## \- Second Step
- [ ] Make tilemaps , and classify textures to separate tilemaps https://github.com/KOBUGE-Games/bob-adventures/issues/6
- [ ] Make maps
## \- Third Step
- [ ] Include ennemies (if possible, as a tilemap and not as an object) https://github.com/KOBUGE-Games/bob-adventures/issues/5 https://github.com/KOBUGE-Games/bob-adventures/issues/6
- [ ] Put the ennemies on the map
## \- Fourth Step
- [ ] Create a menu or a level (or both?) to go from a level to another.
### \- Alpha release
- [ ]

**Comment by ObaniGemini** [comment]
I won't be active for some time because of personnal reasons. Please excuse me.
